catalog:
  '@babel/core': ^7.29.0
  '@babel/eslint-parser': ^7.28.6
  '@babel/plugin-proposal-decorators': ^7.29.0
  '@changesets/changelog-github': ^0.7.0
  '@changesets/cli': ^2.31.0
  '@ember/app-tsconfig': ^2.0.0
  '@eslint/js': ^9.39.4
  '@faker-js/faker': ^10.4.0
  '@floating-ui/dom': ^1.7.6
  '@glint/template': ^1.7.7
  '@lblod/ember-rdfa-editor': 13.10.2-dev.3bc6253600da1a772df1b51f20b264839fb37e05
  '@nullvoxpopuli/ember-composable-helpers': ^5.3.2
  '@tsconfig/ember': ^3.0.12
  changeset: ^0.2.6
  changesets-release-it-plugin: ^0.2.0
  dotenv: ^16.6.1
  ember-basic-dropdown: 8.11.1
  ember-changeset: ^4.2.0
  ember-cli-babel: ^8.3.1
  ember-concurrency: ^4.0.6
  ember-data-resources: ^5.3.2
  ember-intl: ^7.5.0
  ember-modifier: ^4.3.0
  ember-power-select: ^8.12.2
  ember-power-select-with-create: 3.1.0
  ember-resources: ^7.0.7
  ember-sortable: ^5.3.3
  eslint: ^9.39.4
  eslint-config-prettier: ^9.1.2
  eslint-import-resolver-typescript: ^3.10.1
  eslint-plugin-ember: ^12.7.5
  eslint-plugin-import: ^2.32.0
  eslint-plugin-n: ^17.24.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-qunit: ^8.2.6
  globals: ^16.5.0
  prettier: ^3.8.3
  prettier-plugin-ember-template-tag: ^2.1.6
  prosemirror-dev-tools: ^4.3.0
  qunit: ^2.25.0
  qunit-dom: ^3.5.1
  react: 19.2.6
  react-dom: 19.2.6
  sass: ^1.99.0
  stylelint: ^16.26.1
  tracked-built-ins: ^4.1.2
  tracked-toolbox: ^2.2.0
  typescript: ^5.9.3
  typescript-eslint: ^8.59.3
  uuid: ^9.0.1
  webpack: ^5.106.2
  zod: ^3.25.76
overrides:
  '@ember/test-waiters': $@ember/test-waiters
  '@lblod/ember-rdfa-editor': $@lblod/ember-rdfa-editor
  ember-auto-import: $ember-auto-import
  ember-composability-tools>@ember/render-modifiers: ^3.0.0
  ember-headless-form>tracked-built-ins: $tracked-built-ins
  ember-math-helpers: $ember-math-helpers
  ember-truth-helpers: $ember-truth-helpers
  tracked-toolbox: $tracked-toolbox
