steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
      platforms: linux/amd64,linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [feature/*]
