steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO}
      tags: futurenow
      platforms: linux/amd64,linux/arm64
    secrets: [ docker_username, docker_password ]
when:
  branch: futurenow
  event: push
