steps:
  install:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - npm ci
  lint-types:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:types
  lint-js:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:hbs
  lint-prettier:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:prettier
  dependency-lint:
    image: danlynn/ember-cli:5.12.0-node_20.18
    group: lint
    commands:
      - npm run lint:deps
  test:
    image: danlynn/ember-cli:5.12.0-node_20.18
    commands:
      - npm run test:ember
when:
  event: pull_request
