steps:
  install:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm ci
  lint-js:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:js
  lint-hbs:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:hbs
  lint-prettier:
    image: node:20-slim
    group: lint
    commands:
      - npm run lint:prettier
  dependency-lint:
    image: danlynn/ember-cli:4.12.1
    group: lint
    commands:
      - npm run lint:deps
  test:
    image: danlynn/ember-cli:4.12.1
    commands:
      - npm run test:ember
when:
  event: pull_request
