steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  lint-types:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:types
  lint-js:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:js
  lint-hbs:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:hbs
  lint-prettier:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:prettier
  dependency-lint:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:deps
  test:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm test:ember
when:
  - event: pull_request
